# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b #v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: fb24a639f7c938759fe56eeebbb7713b69d60494 #v0.5.1
    hooks:
      - id: go-fmt
      #- id: go-imports
      #- id: no-go-testing
      #- id: golangci-lint
      - id: go-unit-tests

-   repo: local
    hooks:
      - id: license
        name: license
        entry: ./scripts/check-license.sh
        language: script
