---
name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'

permissions: read-all

jobs:
  generate-coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run test
        run: make test-unit
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage
          path: coverage.out
  sonarcloud:
    if: ${{ github.event.pull_request.base.repo.url == github.event.pull_request.head.repo.url }}
    needs: generate-coverage
    uses: complytime/org-infra/.github/workflows/reusable_sonarqube.yml@main
    with:
      sonar_organization: "rh-psce"
      sonar_project_key: "rh-psce_complyctl"
      coverage_artifact_name: "coverage"
      coverage_file_path: "coverage.out"
      language_scanner_property: "sonar.go.coverage.reportPaths"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
